; generated by PrusaSlicer 2.7.4+win64 on 2025-11-16 at 11:48:13 UTC


; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object Shape-Box id:0 copy 0
; stop printing object Shape-Box id:0 copy 0

;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.13.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 X109.557 Y99.7526 W30.8854 H10.4948 ; mesh bed levelling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
M73 P10 R0
M73 Q10 S0

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M907 E538 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0




M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-.8 F2100
M73 P16 R0
M73 Q16 S0
G1 Z.6 F720
G1 X110.139 Y101.278 F10800
M73 P17 R0
G1 Z.2 F720
M73 P19 R0
M73 Q19 S0
G1 E.8 F2100
M73 Q20 S0
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X111.205 Y100.265 E.04611
G1 X112.5 Y99.941 E.04186
G1 X137.5 Y99.941 E.78386
G1 X138.917 Y100.334 E.04611
M73 P23 R0
M73 Q23 S0
G1 X139.931 Y101.4 E.04613
M73 Q24 S0
G1 X140.254 Y102.695 E.04185
G1 X140.254 Y107.305 E.14454
G1 X139.861 Y108.722 E.04611
M73 P24 R0
M73 Q25 S0
G1 X138.795 Y109.735 E.04611
G1 X137.5 Y110.059 E.04186
G1 X112.5 Y110.059 E.78386
G1 X111.083 Y109.666 E.04611
M73 P28 R0
M73 Q29 S0
G1 X110.069 Y108.6 E.04613
G1 X109.746 Y107.305 E.04185
G1 X109.746 Y102.695 E.14454
G1 X110.123 Y101.336 E.04422
M73 P29 R0
M73 Q30 S0
M204 S1000
G1 X110.123 Y101.336 F10800
G1 X110.497 Y101.448
M204 S800
G1 F1200
G1 X110.515 Y101.388 E.00196
G1 X111.56 Y100.512 E.04275
G1 X112.5 Y100.318 E.03009
M73 P30 R0
G1 X137.5 Y100.318 E.78386
G1 X138.807 Y100.71 E.04278
M73 P33 R0
M73 Q34 S0
G1 X139.683 Y101.756 E.04278
G1 X139.877 Y102.695 E.03006
G1 X139.877 Y107.305 E.14454
G1 X139.485 Y108.612 E.04278
M73 P34 R0
M73 Q35 S0
G1 X138.44 Y109.488 E.04275
G1 X137.5 Y109.682 E.03009
G1 X112.5 Y109.682 E.78386
M73 P35 R0
G1 X111.193 Y109.29 E.04278
M73 P38 R0
M73 Q39 S0
G1 X110.317 Y108.244 E.04278
G1 X110.123 Y107.305 E.03006
G1 X110.123 Y102.695 E.14454
G1 X110.479 Y101.505 E.03895
M73 P39 R0
M73 Q40 S0
M204 S1000
;WIPE_START
G1 F8640
G1 X110.497 Y101.448 E-.0138
G1 X110.515 Y101.388 E-.01446
G1 X111.56 Y100.512 E-.31486
G1 X112.5 Y100.318 E-.22162
G1 X113.519 Y100.318 E-.23526
M73 P40 R0
;WIPE_END
G1 Z.6 F720
; printing object Shape-Box id:0 copy 0
G1 X136.713 Y106.518 F10800
G1 Z.2 F720
M73 P41 R0
M73 Q41 S0
G1 E.8 F2100
M204 S800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F1200
M73 Q42 S0
G1 X113.287 Y106.518 E.7345
G1 X113.287 Y103.482 E.09519
M73 P44 R0
M73 Q45 S0
G1 X136.713 Y103.482 E.7345
M73 P45 R0
G1 X136.713 Y105 E.0476
M73 P48 R0
M73 Q48 S0
G1 X136.713 Y106.458 E.04571
M73 Q49 S0
M204 S1000
G1 X136.713 Y106.458 F10800
G1 X137.09 Y106.895
M204 S800
;TYPE:External perimeter
G1 F1200
G1 X112.91 Y106.895 E.75815
G1 X112.91 Y103.105 E.11883
M73 P52 R0
M73 Q52 S0
G1 X137.09 Y103.105 E.75815
M73 Q53 S0
G1 X137.09 Y105 E.05942
M73 P55 R0
M73 Q56 S0
G1 X137.09 Y106.835 E.05754
M73 P56 R0
M204 S1000
;WIPE_START
G1 F8640
G1 X137.09 Y106.895 E-.01385
G1 X133.685 Y106.895 E-.78615
;WIPE_END
G1 Z.6 F720
M73 Q57 S0
G1 X136.543 Y104.423 F10800
G1 Z.2 F720
M73 P57 R0
G1 E.8 F2100
M204 S800
;TYPE:Solid infill
;WIDTH:0.42384
G1 F1200
G1 X135.943 Y103.822 E.0269
G1 X135.404 Y103.822 E.01707
M73 Q58 S0
G1 X136.374 Y104.792 E.04345
G1 X136.374 Y105.33 E.01704
G1 X134.865 Y103.822 E.06757
M73 P58 R0
G1 X134.326 Y103.822 E.01707
G1 X136.374 Y105.869 E.09171
G1 X136.374 Y106.178 E.00979
M73 Q59 S0
G1 X136.144 Y106.178 E.00728
G1 X133.788 Y103.822 E.10553
G1 X133.249 Y103.822 E.01707
M73 P59 R0
G1 X135.605 Y106.178 E.10553
G1 X135.067 Y106.178 E.01704
M73 Q60 S0
G1 X132.71 Y103.822 E.10556
M73 P60 R0
G1 X132.172 Y103.822 E.01704
G1 X134.528 Y106.178 E.10553
M73 Q61 S0
G1 X133.989 Y106.178 E.01707
M73 P61 R0
G1 X131.633 Y103.822 E.10553
G1 X131.094 Y103.822 E.01707
M73 Q62 S0
G1 X133.451 Y106.178 E.10556
G1 X132.912 Y106.178 E.01707
M73 P62 R0
G1 X130.555 Y103.822 E.10556
G1 X130.017 Y103.822 E.01704
M73 Q63 S0
G1 X132.373 Y106.178 E.10553
G1 X131.835 Y106.178 E.01704
M73 P63 R0
G1 X129.478 Y103.822 E.10556
G1 X128.939 Y103.822 E.01707
M73 Q64 S0
G1 X131.296 Y106.178 E.10556
G1 X130.757 Y106.178 E.01707
M73 P64 R0
G1 X128.401 Y103.822 E.10553
G1 X127.862 Y103.822 E.01707
M73 Q65 S0
G1 X130.218 Y106.178 E.10553
M73 P65 R0
G1 X129.68 Y106.178 E.01704
G1 X127.323 Y103.822 E.10556
M73 Q66 S0
G1 X126.785 Y103.822 E.01704
M73 P66 R0
G1 X129.141 Y106.178 E.10553
G1 X128.602 Y106.178 E.01707
M73 Q67 S0
G1 X126.246 Y103.822 E.10553
G1 X125.707 Y103.822 E.01707
M73 P67 R0
G1 X128.064 Y106.178 E.10556
G1 X127.525 Y106.178 E.01707
M73 Q68 S0
G1 X125.168 Y103.822 E.10556
G1 X124.63 Y103.822 E.01704
M73 P68 R0
G1 X126.986 Y106.178 E.10553
G1 X126.448 Y106.178 E.01704
M73 Q69 S0
G1 X124.091 Y103.822 E.10556
G1 X123.552 Y103.822 E.01707
M73 P69 R0
G1 X125.909 Y106.178 E.10556
G1 X125.37 Y106.178 E.01707
M73 Q70 S0
G1 X123.014 Y103.822 E.10553
M73 P70 R0
G1 X122.475 Y103.822 E.01707
G1 X124.831 Y106.178 E.10553
G1 X124.293 Y106.178 E.01704
M73 P71 R0
M73 Q71 S0
G1 X121.936 Y103.822 E.10556
G1 X121.398 Y103.822 E.01704
G1 X123.754 Y106.178 E.10553
M73 Q72 S0
G1 X123.215 Y106.178 E.01707
M73 P72 R0
G1 X120.859 Y103.822 E.10553
G1 X120.32 Y103.822 E.01707
M73 Q73 S0
G1 X122.677 Y106.178 E.10556
G1 X122.138 Y106.178 E.01707
M73 P73 R0
G1 X119.781 Y103.822 E.10556
G1 X119.243 Y103.822 E.01704
M73 Q74 S0
G1 X121.599 Y106.178 E.10553
G1 X121.061 Y106.178 E.01704
M73 P74 R0
G1 X118.704 Y103.822 E.10556
G1 X118.165 Y103.822 E.01707
M73 P75 R0
M73 Q75 S0
G1 X120.522 Y106.178 E.10556
G1 X119.983 Y106.178 E.01707
G1 X117.627 Y103.822 E.10553
G1 X117.088 Y103.822 E.01707
M73 P76 R0
M73 Q76 S0
G1 X119.444 Y106.178 E.10553
G1 X118.906 Y106.178 E.01704
G1 X116.549 Y103.822 E.10556
M73 Q77 S0
G1 X116.011 Y103.822 E.01704
M73 P77 R0
G1 X118.367 Y106.178 E.10553
G1 X117.828 Y106.178 E.01707
M73 Q78 S0
G1 X115.472 Y103.822 E.10553
G1 X114.933 Y103.822 E.01707
M73 P78 R0
G1 X117.29 Y106.178 E.10556
G1 X116.751 Y106.178 E.01707
M73 Q79 S0
G1 X114.394 Y103.822 E.10556
M73 P79 R0
G1 X113.856 Y103.822 E.01704
G1 X116.212 Y106.178 E.10553
G1 X115.673 Y106.178 E.01707
M73 P80 R0
M73 Q80 S0
G1 X113.626 Y104.131 E.09169
G1 X113.626 Y104.67 E.01707
G1 X115.135 Y106.178 E.06757
G1 X114.596 Y106.178 E.01707
M73 Q81 S0
G1 X113.626 Y105.209 E.04343
M73 P81 R0
G1 X113.626 Y105.747 E.01704
G1 X114.227 Y106.348 E.02692
M204 S1000
; stop printing object Shape-Box id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
G1 X113.626 Y105.747 E-.19625
G1 X113.626 Y105.209 E-.12423
G1 X114.596 Y106.178 E-.31659
G1 X115.135 Y106.178 E-.12446
M73 Q82 S0
G1 X115.017 Y106.06 E-.03847
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
M73 P82 R0
G1 Z49.2 F720 ; Move print head further up
M73 P89 R0
M73 Q89 S0
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
M73 Q100 S0
; objects_info = {"objects":[{"name":"Shape-Box id:0 copy 0","polygon":[[137.500,107.305],[112.500,107.305],[112.500,102.695],[137.500,102.695]]}]}
; filament used [mm] = 34.86
; filament used [cm3] = 0.08
; filament used [g] = 0.10
; filament cost = 0.00
; total filament used [g] = 0.10
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 37s
; estimated printing time (silent mode) = 38s
; estimated first layer printing time (normal mode) = 37s
; estimated first layer printing time (silent mode) = 38s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4 and printer_model!=\"MK3.5MMU3\"";"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and printer_notes!~/.*MINIIS.*/ and printer_model!=\"MK3.5\" and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 200
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm SPEED @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.27{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.035{elsif nozzle_diameter[0]==0.5}0.025{elsif nozzle_diameter[0]==0.6}0.02{elsif nozzle_diameter[0]==0.8}0.014{elsif nozzle_diameter[0]==0.25}0.12{elsif nozzle_diameter[0]==0.3}0.08{else}0{endif} ; Filament gcode\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.13.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 X{first_layer_print_min[0]} Y{first_layer_print_min[1]} W{(first_layer_print_max[0]) - (first_layer_print_min[0])} H{(first_layer_print_max[1]) - (first_layer_print_min[1])} ; mesh bed levelling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.6
; support_tree_top_rate = 30%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 50
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
M84 ; disable motors
